version: '3.7'

services:
    node-app:
        container_name: "backend_api"
        build:
            dockerfile: ./Dockerfile.dev
        environment:
            DB_HOST: 'db'
            DB_PORT: '5432'
            DB_USERNAME: 'help_to_grow'
            DB_PASSWORD: 'help_to_grow_db_password'
            DB_DATABASE_NAME: 'help_to_grow'
            DB_DATABASE_DEBUG: 'true'
            JWT_TOKEN_SECRET: 'CVfaGhDjy71MyS34DKRhOZZPoHpdmHqtW2y6rjMtu0qxoe8oDXXcR6nsPpq8mmxS'
            JWT_TOKEN_EXPIRES: '20s'
        ports:
            - 4001:3000
        working_dir: /opt/app
        volumes:
            - ./:/opt/app:ro
            - /opt/app/node_modules
        command: npm run start:dev

    db:
        image: postgres:11.12-alpine
        restart: always
        environment:
            POSTGRES_USER: 'help_to_grow'
            POSTGRES_PASSWORD: 'help_to_grow_db_password'
        logging:
            options:
                max-size: 10m
                max-file: "3"
        ports:
            - 5438:5432
        volumes:
            - ./volumes/postgres-data:/var/lib/postgresql/data

networks:
    default:
        name: help_to_grow_internal_network
