FROM node:14-alpine

WORKDIR /opt/app

# Do not rely on NODE_ENV - exists for performance reasons only
ENV NODE_ENV=development
ENV PORT=3000

ADD . .

RUN apk add --no-cache make gcc g++ python && \
  npm install && \
  npm rebuild bcrypt --build-from-source && \
  apk del make gcc g++ python

EXPOSE 3000

USER node

CMD [ "npm", "start:dev" ]